### ISSUE TITLE
Bug-fix in getting NetCDF map attributes (x,y hardcoded)

### ISSUE THREAD

**Issue by emiliano-gelati** [ec-jrc/lisflood-code#10]
In the function "mapattrNetCDF" (in src/lisflood/global_modules/add1.py), the dimension names 'x' and 'y' had been hard-coded: the model would not work with lon, lat domains.

The rounding operation, which prevents very small rounding errors in coordinates from corrupting the map slicing, was commented out. This feature needs to be restored.

I propose fixing these bugs with the branch commit da07065a7ffd84c00b8ea63b22069e16b860b5a1

**Comment by domeniconappo** [comment]
Hi Emiliano,
I run a test on that branch with no issues.  I think it's good to merge.

PS: You can execute tests with `pytest tests/ -s` from project directory.

**Comment by emiliano-gelati** [comment]
Hi Domenico,
OK - merged in 0e114c1ab149255bcbc03bf012573347156ca0cb
