### ISSUE TITLE
Missing output folder for Drina test

### ISSUE THREAD

**Issue by emiliano-gelati** [ec-jrc/lisflood-code#12]
When running 
`src$ python2 -m pytest ../tests/ -s`
the test crashes because the `tests/data/Drina/outputs` folder is missing, with the following error message:

E                   LisfloodFileError: 
E                   
E                    ======================== LISFLOOD FILE ERROR ===========================
E                   Checking output timeseries 
E                   searching: /home/gelatem/open-source_LISFLOOD/tests/data/Drina/settings/../outputs/disWin.tss
E                   path: /home/gelatem/open-source_LISFLOOD/tests/data/Drina/outputs does not exists

**Comment by domeniconappo** [comment]
@emiliano-gelati 
Thanks for reporting!

BTW, I can force tests to create folder (it's gitignored and not on repository) but to me it sounds better to create output folder if not existing directly in lisflood write functions.

Anyway, I'm going to fix this asap

**Comment by emiliano-gelati** [comment]
OK, I made tentative changes for this issue (972387932876fd8178c797410bcb8d88b9aef2b0) before seeing your reply. Please feel free to discard them and proceed as you think it is best.

**Comment by domeniconappo** [comment]
Thanks! used same approach (f0c6d81d1579e47089e90a1b90199cf1e13ac2e0)

Merged already
