### ISSUE TITLE
 Preparing metadata (setup.py) ... error

### ISSUE THREAD

**Issue by WWWkingMMM** [ec-jrc/lisflood-code#127]
SystemError: gdal-config not found.GDAL seems not installed. Please, install GDAL binaries and libraries for your system and then install the relative pip package.
I have set gdal to the environment, but this error still occurs. How can I solve it?

**Comment by WWWkingMMM** [comment]
I used the code 'conda install - c conda forge gdal' and then used gdal configure -- version. The system displays that 'gdal configure' is not an internal or external command, nor is it a executable program or batch file. But I use conda list - n<your_ environment_ Name>, there is gdal inside

**Comment by doc78** [comment]
Can you please send us further info about operating system? 
The command you should run to check the installation is "gdal-config --version". Please try it and let me know if it is missing.
Furthermore please type the following commands:
conda activate <your_evn_name>
conda env export > myenv.yml
then please attach here the myenv.yml file generated, so I can give it a look

Cheers
Carlo

**Comment by WWWkingMMM** [comment]
Thank you for your reply：
1、I have used the gdal-configure --version line of code, but it does not work. System displays: 'gdal-config' is not an internal or external command, nor is it a runnable program or batch file.
2、This is the information for myenv.yml：

**name: lisflood
channels:
  - conda-forge
  - defaults
dependencies:
  - blosc=1.21.3=hdccc3a2_0
  - boost-cpp=1.78.0=h9f4b32c_3
  - bzip2=1.0.8=h8ffe710_4
  - ca-certificates=2023.5.7=h56e8100_0
  - cairo=1.16.0=hd694305_1014
  - cfitsio=4.1.0=h5a969a9_0
  - curl=8.0.1=h68f0423_0
  - expat=2.5.0=h63175ca_1
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=hab24e00_0
  - fontconfig=2.14.2=hbde0cde_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - freetype=2.12.1=h546665d_1
  - freexl=1.0.6=h67ca5e6_1
  - gdal=3.5.2=py37h1fef14a_5
  - geos=3.11.0=h39d44d4_0
  - geotiff=1.7.1=h4ffd875_4
  - gettext=0.21.1=h5728263_0
  - glib=2.76.2=h12be248_0
  - glib-tools=2.76.2=h12be248_0
  - gst-plugins-base=1.22.0=h001b923_2
  - gstreamer=1.22.0=h6b5321d_2
  - hdf4=4.2.15=h1b1b6ef_5
  - hdf5=1.12.2=nompi_h57737ce_101
  - icu=70.1=h0e60522_0
  - intel-openmp=2023.1.0=h57928b3_46319
  - jpeg=9e=h8ffe710_2
  - kealib=1.4.15=hdf81f3a_1
  - krb5=1.20.1=heb0366b_0
  - lcms2=2.14=h90d422f_0
  - lerc=4.0.0=h63175ca_0
  - libaec=1.0.6=h63175ca_1
  - libblas=3.9.0=16_win64_mkl
  - libcblas=3.9.0=16_win64_mkl
  - libclang=15.0.7=default_h77d9078_1
  - libclang13=15.0.7=default_h77d9078_1
  - libcurl=8.0.1=h68f0423_0
  - libdeflate=1.18=hcfcfb64_0
  - libexpat=2.5.0=h63175ca_1
  - libffi=3.4.2=h8ffe710_5
  - libgdal=3.5.2=h283e77c_5
  - libglib=2.76.2=he8f3873_0
  - libhwloc=2.9.1=h51c2c0f_0
  - libiconv=1.17=h8ffe710_0
  - libjpeg-turbo=2.1.4=hcfcfb64_0
  - libkml=1.3.0=hf2ab4e4_1015
  - liblapack=3.9.0=16_win64_mkl
  - libnetcdf=4.8.1=nompi_h8c042bf_106
  - libogg=1.3.4=h8ffe710_1
  - libpng=1.6.39=h19919ed_0
  - libpq=14.5=ha9684e8_5
  - librttopo=1.1.0=h2842628_11
  - libspatialite=5.0.1=hd560d62_21
  - libsqlite=3.41.2=hcfcfb64_1
  - libssh2=1.10.0=h9a1e1f7_3
  - libtiff=4.4.0=h8a3f274_2
  - libvorbis=1.3.7=h0e60522_0
  - libwebp-base=1.3.0=hcfcfb64_0
  - libxml2=2.10.4=hc3477c8_0
  - libzip=1.9.2=h519de47_1
  - libzlib=1.2.13=hcfcfb64_4
  - lz4-c=1.9.4=hcfcfb64_0
  - mkl=2022.1.0=h6a75c08_874
  - numpy=1.21.6=py37h2830a78_0
  - openjpeg=2.5.0=hc9384bd_1
  - openssl=3.1.0=hcfcfb64_3
  - pcraster=4.3.3=py37hb2cefe2_3
  - pcre=8.45=h0e60522_0
  - pcre2=10.40=h17e33f8_0
  - pip=23.1.2=pyhd8ed1ab_0
  - pixman=0.40.0=h8ffe710_0
  - poppler=22.10.0=ha6c1112_0
  - poppler-data=0.4.12=hd8ed1ab_0
  - postgresql=14.5=hd87cd2b_5
  - proj=9.1.0=h3863b3b_0
  - pthreads-win32=2.9.1=hfa6e2cd_3
  - python=3.7.12=h900ac77_100_cpython
  - python_abi=3.7=3_cp37m
  - qt-main=5.15.8=h720456b_6
  - setuptools=67.7.2=pyhd8ed1ab_0
  - snappy=1.1.10=hfb803bf_0
  - sqlite=3.41.2=hcfcfb64_1
  - tbb=2021.9.0=h91493d7_0
  - tiledb=2.11.3=h3132609_1
  - ucrt=10.0.22621.0=h57928b3_0
  - vc=14.3=hb25d44b_16
  - vc14_runtime=14.34.31931=h5081d32_16
  - vs2015_runtime=14.34.31931=hed1258a_16
  - wheel=0.40.0=pyhd8ed1ab_0
  - xerces-c=3.2.4=h63175ca_2
  - xz=5.2.6=h8d14728_0
  - zlib=1.2.13=hcfcfb64_4
  - zstd=1.5.2=h12be248_6
prefix: E:\miniconda\envs\lisflood**

Thanks

**Comment by doc78** [comment]
It seems that you are running in Windows operating systems. I'm sorry but as written in Readme file ("IMPORTANT NOTE 1") we are not able to give support in Windows operating system

**Comment by WWWkingMMM** [comment]
So do I need to install a Linux virtual machine and run it ?

**Comment by doc78** [comment]
Yes, you can run it in a Linux Virtual machine (e.g. Ubuntu on VirtualBox or VMWare) or in a native Linux operating system.

**Comment by WWWkingMMM** [comment]
Thank you for your answers to my recent questions. Have a nice day.

**Comment by WWWkingMMM** [comment]
Sorry to bother you again
I have successfully installed lisflood on Linux and showed Arguments list. However, I cannot start using the lisflood -v xxx. par or -v xxx..par, or --veryquiet xxx.par command, which shows no command found or No such file or directory: '-v'

**Comment by doc78** [comment]
Please try the following syntax for the lisflood command:

lisflood <your_setting_file.xml> -v

Thanks
Carlo
