### ISSUE TITLE
issues with namespaces

### ISSUE THREAD

**Issue by menta78** [ec-jrc/lisflood-code#13]
If I follow the quickstart on the guide, and launch the command

python src/lisflood/lisf1.py tests/data/Drina/settings/lisfloodSettings_cold_day_base.xml

from the root folder of the repo, I have the error
ImportError: No module named lisflood.hydrological_modules.miscInitial

Instead, lisf1.py works if launched from the src folder.

This is because lisf1.py and Lisflood_initial.py and others are already located in the lisflood directory, and see directly the content of hydrological_modules. So, the import instruction should be something like 

from hydrological_modules import miscInitial
rather than
from lisflood.hydrological_modules import miscInitial

A solution alternative to changing the import command could be adding the the src/ directory to the PYTHONPATH

**Comment by domeniconappo** [comment]
We went adding content of src folder to the pythonpath. Testing it.
