### ISSUE TITLE
Lisflood for small basins

### ISSUE THREAD

**Issue by Sailor596** [ec-jrc/lisflood-code#132]
Hi, can I use Lisflood for a basin with an area of 2000 m2?

**Comment by StefaniaGrimaldi** [comment]
Dear @Sailor596,

thank you for your enquiry.

In principle, there is no lower limit on the area that can be modelled by LISFLOOD OS.

LISFLOOD OS is a spatially distributed model. Any model set-up must include a sufficient number of cells to allow the adequate modelling of the hydrological processes which are relevant for the area.
There is no official rule to define the adequate number: this number depends on the features of the modelled area, on the scope of the exercise, on the data which are available to prepare the model set-up.
As a very rough indication, we do not recommend using less than 10-15 cells.

For this reason, you should prepare the input data set (static maps and meteorological forcings: https://ec-jrc.github.io/lisflood-code/3_step4_preparing-input-files/) with adequate resolution.

Albeit at the JRC we use LISFLOOD OS mainly at the European and at the global domain with km resolution, we are aware that other LISFLOOD OS users are implementing the model with 10m resolution.

Please do not hesitate to contact us for further questions,
Kind regards,
Stefania
