### ISSUE TITLE
A question about FDM of diffusive wave in channel of LISFLOOD-FP5.9.6

### ISSUE THREAD

**Issue by DD-WU** [ec-jrc/lisflood-code#134]
// Setting the odd rows of the compact form of the Jacobian [Continuity Equation]
    J[i+1][0]=0;
    J[i+1][1]=0.5/dt;
    J[i+1][2]=-th/dx;
    J[i+1][3]=J[i+1][1];
    J[i+1][4]=-J[i+1][2];

// Setting the even rows of the compact form of the Jacobian [Momentum Equation]
    a=th*(xn[i]+xn[i+2])/2+(1-th)*(x[i]+x[i+2])/2;
    q=th*(xn[i+1]+xn[i+3])/2+(1-th)*(x[i+1]+x[i+3])/2;
    J[i+2][0]=th/(w*dx)+10*n2w43th*fabs(q)*q/(6*pow(a, (13./3.)));
    J[i+2][1]=-n2w43th*fabs(q)/pow(a,(10./3.));
    J[i+2][2]=-J[i+2][0];
    J[i+2][3]=J[i+2][1];
    J[i+2][4]=0;

In the version of c++,  LISFLOOD-FP do  channel routing by diffusive wave. And use implicit newton raphson scheme to solve it. I don't quite understand why the differential terms can be replaced by these difference terms, is there a detailed explanation of why the terms of J[i+1][i] can be written in this form please? For example, For the term J[i+1][2] = -th/dx, which of St. Venant's equations is it differencing, and why is it possible to do so.

**Comment by DD-WU** [comment]
Or what is the name of this discretization method, is it pressiman implicit difference?

**Comment by StefaniaGrimaldi** [comment]
Dear @DD-WU, 
please be aware that this is the repository of the LISFLOOD open source rainfall-runoff hydrological model. You can find the documentation here https://ec-jrc.github.io/lisflood-model/
You are seeking support for the use of LISFLOOD-FP, which is a different model.
Kind regards,
Stefania
