### ISSUE TITLE
KeyError: 'EWRef'

### ISSUE THREAD

**Issue by diogoamore** [ec-jrc/lisflood-code#135]
Dear friends,

Many thanks for the awesome job with Lisflood. I am currently running smoothly in a server but am also trying to install it in a side desktop. I followed the same steps I used for the server while installing in the desktop. However the following error popped up just as I try to run the cold.xml at the final installation step:

**Traceback (most recent call last):
  File "/home/diogo/miniconda3/envs/lisflood38/lisflood-code-4.1.3/src/lisf1.py", line 34, in <module>
    sys.exit(main())
  File "/home/diogo/miniconda3/envs/lisflood38/lisflood-code-4.1.3/src/lisflood/main.py", line 224, in main
    lisfloodexe(lissettings)
  File "/home/diogo/miniconda3/envs/lisflood38/lisflood-code-4.1.3/src/lisflood/main.py", line 155, in lisfloodexe
    model_to_run.run()
  File "/home/diogo/miniconda3/envs/lisflood38/lisflood-code-4.1.3/src/lisflood/global_modules/zusatz.py", line 139, in run
    self._runDynamic()
  File "/home/diogo/miniconda3/envs/lisflood38/lib/python3.8/site-packages/pcraster/framework/frameworkBase.py", line 371, in _runDynamic
    self._userModel().dynamic()
  File "/home/diogo/miniconda3/envs/lisflood38/lisflood-code-4.1.3/src/lisflood/Lisflood_dynamic.py", line 107, in dynamic
    self.soilloop_module.dynamic_canopy()
  File "/home/diogo/miniconda3/envs/lisflood38/lisflood-code-4.1.3/src/lisflood/hydrological_modules/soilloop.py", line 532, in dynamic_canopy
    TaInterceptionMax = nx.evaluate('EWRef * one_minus_LAITerm', global_dict={'EWRef': self.var.EWRef[None]})
  File "/home/diogo/miniconda3/envs/lisflood38/lib/python3.8/site-packages/numexpr/necompiler.py", line 941, in evaluate
    return re_evaluate(local_dict=local_dict, _frame_depth=_frame_depth)
  File "/home/diogo/miniconda3/envs/lisflood38/lib/python3.8/site-packages/numexpr/necompiler.py", line 969, in re_evaluate
    args = getArguments(argnames, local_dict, _frame_depth=_frame_depth)
  File "/home/diogo/miniconda3/envs/lisflood38/lib/python3.8/site-packages/numexpr/necompiler.py", line 755, in getArguments
    a = global_dict[name]
KeyError: 'EWRef'**

Here it is the pip list:

**attrs              23.1.0
beautifulsoup4     4.12.2
certifi            2023.7.22
cftime             1.6.2
click              8.1.7
cloudpickle        2.2.1
coverage           7.3.0
Cython             3.0.0
dask               2023.5.0
exceptiongroup     1.1.3
fsspec             2023.6.0
future             0.18.3
GDAL               3.7.1.1
importlib-metadata 4.13.0
iniconfig          2.0.0
lisflood-utilities 0.12.21
llvmlite           0.40.1
locket             1.0.0
lxml               4.9.3
more-itertools     10.1.0
netCDF4            1.6.4
nine               1.1.0
numba              0.57.1
numexpr            2.8.5
numpy              1.24.4
packaging          23.1
pandas             1.5.3
partd              1.4.0
pathlib2           2.3.7.post1
pip                23.2.1
pkginfo            1.9.6
pluggy             1.2.0
py                 1.11.0
pyparsing          3.1.1
pyproj             3.5.0
pytest             7.4.0
pytest-cov         4.1.0
pytest-mock        3.11.1
python-dateutil    2.8.2
pytz               2023.3
PyYAML             6.0.1
setuptools         68.1.2
six                1.16.0
soupsieve          2.4.1
toml               0.10.2
tomli              2.0.1
toolz              0.12.0
tzdata             2023.3
wheel              0.41.2
xarray             2023.1.0
zipp               3.16.2**

Here it is the conda list:

**_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
alsa-lib                  1.2.8                h166bdaf_0    conda-forge
attr                      2.5.1                h166bdaf_1    conda-forge
attrs                     23.1.0                   pypi_0    pypi
beautifulsoup4            4.12.2                   pypi_0    pypi
blosc                     1.21.4               h0f2a231_0    conda-forge
boost-cpp                 1.78.0               h6582d0a_3    conda-forge
bzip2                     1.0.8                h7f98852_4    conda-forge
c-ares                    1.19.1               hd590300_0    conda-forge
ca-certificates           2023.7.22            hbcca054_0    conda-forge
cairo                     1.16.0            hbbf8b49_1016    conda-forge
certifi                   2023.7.22                pypi_0    pypi
cfitsio                   4.2.0                hd9d235c_0    conda-forge
cftime                    1.6.2                    pypi_0    pypi
click                     8.1.7                    pypi_0    pypi
cloudpickle               2.2.1                    pypi_0    pypi
coverage                  7.3.0                    pypi_0    pypi
cython                    3.0.0                    pypi_0    pypi
dask                      2023.5.0                 pypi_0    pypi
dbus                      1.13.6               h5008d03_3    conda-forge
exceptiongroup            1.1.3                    pypi_0    pypi
expat                     2.5.0                hcb278e6_1    conda-forge
font-ttf-dejavu-sans-mono 2.37                 hab24e00_0    conda-forge
font-ttf-inconsolata      3.000                h77eed37_0    conda-forge
font-ttf-source-code-pro  2.038                h77eed37_0    conda-forge
font-ttf-ubuntu           0.83                 hab24e00_0    conda-forge
fontconfig                2.14.2               h14ed4e7_0    conda-forge
fonts-conda-ecosystem     1                             0    conda-forge
fonts-conda-forge         1                             0    conda-forge
freetype                  2.12.1               hca18f0e_1    conda-forge
freexl                    1.0.6                h166bdaf_1    conda-forge
fsspec                    2023.6.0                 pypi_0    pypi
future                    0.18.3                   pypi_0    pypi
gdal                      3.7.1.1                  pypi_0    pypi
geos                      3.12.0               h59595ed_0    conda-forge
geotiff                   1.7.1               h22adcc9_11    conda-forge
gettext                   0.21.1               h27087fc_0    conda-forge
giflib                    5.2.1                h0b41bf4_3    conda-forge
glib                      2.76.4               hfc55251_0    conda-forge
glib-tools                2.76.4               hfc55251_0    conda-forge
graphite2                 1.3.13            h58526e2_1001    conda-forge
gst-plugins-base          1.22.3               h938bd60_1    conda-forge
gstreamer                 1.22.3               h977cf35_1    conda-forge
harfbuzz                  7.3.0                hdb3a94d_0    conda-forge
hdf4                      4.2.15               h501b40f_6    conda-forge
hdf5                      1.14.1          nompi_h4f84152_100    conda-forge
icu                       72.1                 hcb278e6_0    conda-forge
importlib-metadata        4.13.0                   pypi_0    pypi
iniconfig                 2.0.0                    pypi_0    pypi
json-c                    0.16                 hc379101_0    conda-forge
kealib                    1.5.1                h3e6883b_4    conda-forge
keyutils                  1.6.1                h166bdaf_0    conda-forge
krb5                      1.20.1               h81ceb04_0    conda-forge
lame                      3.100             h166bdaf_1003    conda-forge
lcms2                     2.15                 haa2dc70_1    conda-forge
ld_impl_linux-64          2.40                 h41732ed_0    conda-forge
lerc                      4.0.0                h27087fc_0    conda-forge
libaec                    1.0.6                hcb278e6_1    conda-forge
libarchive                3.6.2                h039dbb9_1    conda-forge
libblas                   3.9.0           17_linux64_openblas    conda-forge
libcap                    2.69                 h0f662aa_0    conda-forge
libcblas                  3.9.0           17_linux64_openblas    conda-forge
libclang                  16.0.6          default_h1cdf331_1    conda-forge
libclang13                16.0.6          default_h4d60ac6_1    conda-forge
libcups                   2.3.3                h36d4200_3    conda-forge
libcurl                   8.1.2                h409715c_0    conda-forge
libdeflate                1.18                 h0b41bf4_0    conda-forge
libedit                   3.1.20191231         he28a2e2_2    conda-forge
libev                     4.33                 h516909a_1    conda-forge
libevent                  2.1.12               hf998b51_1    conda-forge
libexpat                  2.5.0                hcb278e6_1    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libflac                   1.4.3                h59595ed_0    conda-forge
libgcc-ng                 13.1.0               he5830b7_0    conda-forge
libgcrypt                 1.10.1               h166bdaf_0    conda-forge
libgdal                   3.7.1                ha66225b_1    conda-forge
libgfortran-ng            13.1.0               h69a702a_0    conda-forge
libgfortran5              13.1.0               h15d22d2_0    conda-forge
libglib                   2.76.4               hebfc3b9_0    conda-forge
libglu                    9.0.0             hac7e632_1002    conda-forge
libgomp                   13.1.0               he5830b7_0    conda-forge
libgpg-error              1.47                 h71f35ed_0    conda-forge
libiconv                  1.17                 h166bdaf_0    conda-forge
libjpeg-turbo             2.1.5.1              h0b41bf4_0    conda-forge
libkml                    1.3.0             h37653c0_1015    conda-forge
liblapack                 3.9.0           17_linux64_openblas    conda-forge
libllvm16                 16.0.6               h5cf9203_2    conda-forge
libnetcdf                 4.9.2           nompi_he09a3a9_107    conda-forge
libnghttp2                1.52.0               h61bc06f_0    conda-forge
libnsl                    2.0.0                h7f98852_0    conda-forge
libogg                    1.3.4                h7f98852_1    conda-forge
libopenblas               0.3.23          pthreads_h80387f5_0    conda-forge
libopus                   1.3.1                h7f98852_1    conda-forge
libpng                    1.6.39               h753d276_0    conda-forge
libpq                     15.3                 hbcd7760_1    conda-forge
librttopo                 1.1.0               hb58d41b_14    conda-forge
libsndfile                1.2.2                hbc2eb40_0    conda-forge
libspatialite             5.0.1               h15f6e67_28    conda-forge
libsqlite                 3.42.0               h2797004_0    conda-forge
libssh2                   1.11.0               h0841786_0    conda-forge
libstdcxx-ng              13.1.0               hfd8a6a1_0    conda-forge
libsystemd0               254                  h3516f8a_0    conda-forge
libtiff                   4.5.1                h8b53f26_0    conda-forge
libuuid                   2.38.1               h0b41bf4_0    conda-forge
libvorbis                 1.3.7                h9c3ff4c_0    conda-forge
libwebp-base              1.3.1                hd590300_0    conda-forge
libxcb                    1.15                 h0b41bf4_0    conda-forge
libxkbcommon              1.5.0                h5d7e998_3    conda-forge
libxml2                   2.11.5               h0d562d8_0    conda-forge
libzip                    1.10.1               h2629f0a_0    conda-forge
libzlib                   1.2.13               hd590300_5    conda-forge
lisflood-utilities        0.12.21                  pypi_0    pypi
llvmlite                  0.40.1                   pypi_0    pypi
locket                    1.0.0                    pypi_0    pypi
lxml                      4.9.3                    pypi_0    pypi
lz4-c                     1.9.4                hcb278e6_0    conda-forge
lzo                       2.10              h516909a_1000    conda-forge
more-itertools            10.1.0                   pypi_0    pypi
mpg123                    1.31.3               hcb278e6_0    conda-forge
mysql-common              8.0.33               hf1915f5_2    conda-forge
mysql-libs                8.0.33               hca2cd23_2    conda-forge
ncurses                   6.4                  hcb278e6_0    conda-forge
netcdf4                   1.6.4                    pypi_0    pypi
nine                      1.1.0                    pypi_0    pypi
nspr                      4.35                 h27087fc_0    conda-forge
nss                       3.92                 h1d7d5a4_0    conda-forge
numba                     0.57.1                   pypi_0    pypi
numexpr                   2.8.5                    pypi_0    pypi
numpy                     1.24.4           py38h59b608b_0    conda-forge
openjpeg                  2.5.0                hfec8fc6_2    conda-forge
openssl                   3.1.2                hd590300_0    conda-forge
packaging                 23.1                     pypi_0    pypi
pandas                    1.5.3                    pypi_0    pypi
partd                     1.4.0                    pypi_0    pypi
pathlib2                  2.3.7.post1              pypi_0    pypi
pcraster                  4.4.0            py38hf3a9708_3    conda-forge
pcre2                     10.40                hc3806b6_0    conda-forge
pip                       23.2.1             pyhd8ed1ab_0    conda-forge
pixman                    0.40.0               h36c2ea0_0    conda-forge
pkginfo                   1.9.6                    pypi_0    pypi
pluggy                    1.2.0                    pypi_0    pypi
poppler                   23.07.0              hd18248d_0    conda-forge
poppler-data              0.4.12               hd8ed1ab_0    conda-forge
postgresql                15.3                 hd458b1d_1    conda-forge
proj                      9.2.1                ha643af7_0    conda-forge
pthread-stubs             0.4               h36c2ea0_1001    conda-forge
pulseaudio-client         16.1                 hb77b528_4    conda-forge
py                        1.11.0                   pypi_0    pypi
pyparsing                 3.1.1                    pypi_0    pypi
pyproj                    3.5.0                    pypi_0    pypi
pytest                    7.4.0                    pypi_0    pypi
pytest-cov                4.1.0                    pypi_0    pypi
pytest-mock               3.11.1                   pypi_0    pypi
python                    3.8.17          he550d4f_0_cpython    conda-forge
python-dateutil           2.8.2                    pypi_0    pypi
python_abi                3.8                      3_cp38    conda-forge
pytz                      2023.3                   pypi_0    pypi
pyyaml                    6.0.1                    pypi_0    pypi
qt-main                   5.15.8              h01ceb2d_12    conda-forge
readline                  8.2                  h8228510_1    conda-forge
setuptools                68.1.2             pyhd8ed1ab_0    conda-forge
six                       1.16.0                   pypi_0    pypi
snappy                    1.1.10               h9fff704_0    conda-forge
soupsieve                 2.4.1                    pypi_0    pypi
sqlite                    3.42.0               h2c6b66d_0    conda-forge
tiledb                    2.16.3               hf0b6e87_1    conda-forge
tk                        8.6.12               h27826a3_0    conda-forge
toml                      0.10.2                   pypi_0    pypi
tomli                     2.0.1                    pypi_0    pypi
toolz                     0.12.0                   pypi_0    pypi
tzcode                    2023c                h0b41bf4_0    conda-forge
tzdata                    2023.3                   pypi_0    pypi
wheel                     0.41.2             pyhd8ed1ab_0    conda-forge
xarray                    2023.1.0                 pypi_0    pypi
xcb-util                  0.4.0                hd590300_1    conda-forge
xcb-util-image            0.4.0                h8ee46fc_1    conda-forge
xcb-util-keysyms          0.4.0                h8ee46fc_1    conda-forge
xcb-util-renderutil       0.3.9                hd590300_1    conda-forge
xcb-util-wm               0.4.1                h8ee46fc_1    conda-forge
xerces-c                  3.2.4                h8d71039_2    conda-forge
xkeyboard-config          2.39                 hd590300_0    conda-forge
xorg-kbproto              1.0.7             h7f98852_1002    conda-forge
xorg-libice               1.1.1                hd590300_0    conda-forge
xorg-libsm                1.2.4                h7391055_0    conda-forge
xorg-libx11               1.8.6                h8ee46fc_0    conda-forge
xorg-libxau               1.0.11               hd590300_0    conda-forge
xorg-libxdmcp             1.1.3                h7f98852_0    conda-forge
xorg-libxext              1.3.4                h0b41bf4_2    conda-forge
xorg-libxrender           0.9.11               hd590300_0    conda-forge
xorg-renderproto          0.11.1            h7f98852_1002    conda-forge
xorg-xextproto            7.3.0             h0b41bf4_1003    conda-forge
xorg-xf86vidmodeproto     2.3.1             h7f98852_1002    conda-forge
xorg-xproto               7.0.31            h7f98852_1007    conda-forge
xz                        5.2.6                h166bdaf_0    conda-forge
zipp                      3.16.2                   pypi_0    pypi
zlib                      1.2.13               hd590300_5    conda-forge
zstd                      1.5.2                hfc55251_7    conda-forge**

Much appreaciate any feedback, because so far I haven't managed to figure it out what could be going on.

**Comment by doc78** [comment]
Hi @diogoamore 
Can you please share your cold.xml file you are trying to run? 
Thanks
Carlo

**Comment by diogoamore** [comment]
I am using the XML files as they come from the JRC github page for each version I tried (4.1.1 and 4.1.3). Here it is the cold.xml from both versions.

[cold_xml.zip](https://github.com/ec-jrc/lisflood-code/files/12454902/cold_xml.zip)
