### ISSUE TITLE
Issues with Lisflood installation

### ISSUE THREAD

**Issue by marinewave** [ec-jrc/lisflood-code#136]
I am unable to install the LISFLOOD. The below-mentioned error is coming up every time I am trying to install.

Collecting git+https://github.com/jsosa/LFPtools.git
  Cloning https://github.com/jsosa/LFPtools.git to /tmp/pip-req-build-npyz59l3
  Running command git clone --filter=blob:none --quiet https://github.com/jsosa/LFPtools.git /tmp/pip-req-build-npyz59l3
  Resolved https://github.com/jsosa/LFPtools.git to commit dc2497d41d0d40545360406c06c6fb07735e1633
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: lfptools
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  Building wheel for lfptools (setup.py) ... error
  ERROR: Failed building wheel for lfptools
  Running setup.py clean for lfptools
Failed to build lfptools
ERROR: Could not build wheels for lfptools, which is required to install pyproject.toml-based projects

**Comment by doc78** [comment]
Dear @marinewave 

I see LFPtools uses LISFLOOD-FP, that is a different software. This github page is related to Lisflood-OS
