### ISSUE TITLE
Lisflood Installation Error

### ISSUE THREAD

**Issue by marinewave** [ec-jrc/lisflood-code#137]
Dear friend,
I am getting the error constantly as mentioned below, 

 Cloning https://github.com/jsosa/LFPtools.git to c:\users\raja~1.cha\appdata\local\temp\pip-req-build-z40_bd00
  Running command git clone --filter=blob:none --quiet https://github.com/jsosa/LFPtools.git 'C:\Users\RAJA~1.CHA\AppData\Local\Temp\pip-req-build-z40_bd00'
  Resolved https://github.com/jsosa/LFPtools.git to commit dc2497d41d0d40545360406c06c6fb07735e1633
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 36, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\RAJA~1.CHA\AppData\Local\Temp\pip-req-build-z40_bd00\setup.py", line 3, in <module>
          from Cython.Build import cythonize
      ModuleNotFoundError: No module named 'Cython'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by doc78** [comment]
Dear @marinewave 

I see LFPtools uses LISFLOOD-FP, that is a different software. This github page is related to Lisflood-OS
