### ISSUE TITLE
Total water storage output

### ISSUE THREAD

**Issue by emiliano-gelati** [ec-jrc/lisflood-code#143]
Hi,

I am going to to provide total water storage maps for a project (Stars4water). As far as I can see, this output is not produced by LISFLOOD yet. If so, and if you are not already working on it, I could prepare a pull request on it.

I see water storage components (`ChannelStoredM3` and `HillslopeStoredM3`) are computed in the [waterbalance](https://github.com/ec-jrc/lisflood-code/blob/master/src/lisflood/hydrological_modules/waterbalance.py#L146-L160) module. Then these could be summed into a new variable (e.g. `TotalWaterStorage`). Perhaps a new reporting option (e.g. `repTotalWaterStorage`) is needed due to file size.

What do you think?

Best regards,
Emiliano

**Comment by salampe** [comment]
Emiliano,

This would be fantastic! We have also other LISFLOOD users (GFZ Potsdam) that look at total water storage and compare it with GRACE measurements at global level.  This new reporting option would be highly appreciated for sure!

Peter

**Comment by emiliano-gelati** [comment]
Great, then I will work on it and come up with a proposal.

I have a question (maybe for @doc78 or @StefaniaGrimaldi): should I use "master" as a starting point for development or another branch?

Emiliano

**Comment by doc78** [comment]
Yes, you can use both master or development branch as a starting point. In any case I will merge on development branch before releasing any new version on master
