### ISSUE TITLE
Running LIFLOOD in GPUs

### ISSUE THREAD

**Issue by EdgarEspitia** [ec-jrc/lisflood-code#151]
Dear LISFLOOD development team,

I was wondering if there is any difference in the setup, performance or results when running LISFLOOD in GPUs? Is there a suggested test? 

Thanks you

Best regards,
Edgar

**Comment by doc78** [comment]
Dear @EdgarEspitia 

Lisflood code and related libraries are executed on CPU and leverage on multiple CPU cores, but the instructions are not made to be executed on GPUs, so you will not have any improvement when adding GPUs to your system. 
Even if some functions could be enhanced and parallelized further by the use of the GPU, this require special code and libraries to be added, and the current Lisflood code do not use them. 

Best regards
Carlo

**Comment by EdgarEspitia** [comment]
Dear @doc78 ,

LISFLOOD can run on GPUs in the same way as it runs on CPUs, but no performance gain or numerical loss. So is it safe to run on GPUs?

Best regards,
Edgar

**Comment by doc78** [comment]
Dear @EdgarEspitia
Lisflood code do not use GPU: it will only use the available CPU ignoring GPU.
Best regards
Carlo
