### ISSUE TITLE
Error running usecase lisflood 4.3.1 

### ISSUE THREAD

**Issue by EdgarEspitia** [ec-jrc/lisflood-code#152]
Dear LISFLOOD development team,

I am testing a fresh installation of LISFLOOD 4.3.1 with the use case  LF_ETRS89, so I ran the prerun `settings_ETRS89-PreRun.xml` but I got the error `KeyError: 'OutputMapsDataType'`.   LISFLOOD is able to write the discharge, dis.tss, along all the time steps, but it is a little bit different from the reference. You can have a look at the attached files.

Log report
[test_lisflood_pre_run_usecase_LF_ETRS89.log](https://github.com/ec-jrc/lisflood-code/files/14403096/test_lisflood_pre_run_usecase_LF_ETRS89.log)

Reported discharge 
[dis_test_cpu_LF_ETRS89_pre_run.tss.txt](https://github.com/ec-jrc/lisflood-code/files/14402989/dis_test_cpu_LF_ETRS89_pre_run.tss.txt)

Reference discharge
[dis_reference_LF_ETRS89.tss.txt](https://github.com/ec-jrc/lisflood-code/files/14402998/dis_reference_LF_ETRS89.tss.txt)

Thank you

Best regards,
Edgar

**Comment by doc78** [comment]
Dear Edgar

You should add OutputMapsDataType field in your xml file, just after OutputMapsChunks, in two section (see lisflood_reference xml file):

Line 153:

<comment>
The option "OutputMapsDataType" sets the output data type and may take the following values:
    - "float64"
    - "float32"
</comment>
<textvar name="OutputMapsDataType" value="float64"/>

Line 1714:
<textvar name="OutputMapsDataType" value="$(OutputMapsDataType)"/>

Regarding the differences, can you please try to run the version 4.2.0 (pip install lisflood-model==4.2.0) on the same machine and let me know the TSS results?

Thank you
Carlo

**Comment by EdgarEspitia** [comment]
Dear Carlo,

I have edited lines 119 to 149 and 1566  in the  prerun settings file [settings_ETRS89-PreRun.xml.txt](https://github.com/ec-jrc/lisflood-code/files/14406526/settings_ETRS89-PreRun.xml.txt), but I am not changing the run settings file, [settings_ETRS89-Run.xml.txt](https://github.com/ec-jrc/lisflood-code/files/14406555/settings_ETRS89-Run.xml.txt), so it worked, but should I modify the run settings file to avoid unexpected behavior? 

The mismatch between the reference and calculated discharge is solved, the problem was that I was comparing the dis.tss file generated in the pre-run instead of the one generated in the run. I did not try the the version 4.2.0.

Thanks  a lot
Edgar

**Comment by EdgarEspitia** [comment]
Dear Carlo,

Now I am trying the modified settings file [01_weser_settings-PreRun.xml.txt](https://github.com/ec-jrc/lisflood-code/files/14416527/01_weser_settings-PreRun.xml.txt)  in one of my study catchments and I get the error `KeyError: 'OutputMapsChunks'`  [01_weser_cpu_9063680.out.txt](https://github.com/ec-jrc/lisflood-code/files/14416540/01_weser_cpu_9063680.out.txt) 

Thanks a lot
Edgar

**Comment by EdgarEspitia** [comment]
Dear Carlo,

I solved the problems
- For the ETRS89 use case  I was using the settings files for LISFLOOD version 4.1.0, instead of the version 4.3.1, so I added the  missing variables, OutputMapsChunks and OutputMapsDataType, in both settings files,    [settings_ETRS89-PreRun.xml.txt](https://github.com/ec-jrc/lisflood-code/files/14421245/settings_ETRS89-PreRun.xml.txt) and [settings_ETRS89-Run.xml.txt](https://github.com/ec-jrc/lisflood-code/files/14421253/settings_ETRS89-Run.xml.txt). 
- In my catchment setup, [01_weser_settings-PreRun.xml.txt](https://github.com/ec-jrc/lisflood-code/files/14421678/01_weser_settings-PreRun.xml.txt), a call to the variable **OutputMapsChunks** variable was missing, so I added it to the prerun and run xml files.

Now LISFLOOD version 4.3.1 is running!


But I get the warning:
```
/home/edgar/hydromodelling/conda_venvs/lisflood_code_4_3_1/lib/python3.7/site-packages/xarray/core/indexing.py:1227: PerformanceWarning: Slicing is producing a large chunk. To accept the large
chunk and silence this warning, set the option
    >>> with dask.config.set(**{'array.slicing.split_large_chunks': False}):
    ...     array[indexer]
To avoid creating the large chunks, set the option
    >>> with dask.config.set(**{'array.slicing.split_large_chunks': True}):
    ...     array[indexer]
  return self.array[key]
```
[01_weser_9068651.out.txt](https://github.com/ec-jrc/lisflood-code/files/14421694/01_weser_9068651.out.txt)


I am thinking of modifying the  **NetCDFTimeChunks** variable, then  what criteria is advisable to define the chunk size or is it better to let xarray to decide?

Thanks a lot!!!

Edgar

**Comment by doc78** [comment]
Dear Edgar

Optimal chunk size really depend on your hardware and the size of your simulations. Here you can find some guidelines for chunck size:

https://docs.dask.org/en/latest/array-chunks.html#array-chunks

If you have enough RAM and you are running a single catchment o a small region, you can use "-1", to it will read all the dynamic meteo maps upfront. If you are running big regions and you have memory issues, you can use "auto" or specify a number to avoid reading all the timesteps in memory. A small chunk size will results in more disk access to read the NetCDF dynamic map values.

Cheers
Carlo
