### ISSUE TITLE
Question about crop coefficient  fraction maps

### ISSUE THREAD

**Issue by pierrejonathan** [ec-jrc/lisflood-code#160]
Hello,

I am preparing a table that summarizes the mean Kc (crop coefficient) values ​​per land cover type in my study area. For the land cover classes, I have to use the LULC classification of the governing bodies of my study area which is different for what was used for your product I believe. It contains more than 801 detailed classes. That said, I am still able to summarize them in the following classes: 

- Forest, 
- agricultural, 
- humid/wetland, 
- anthropogenic, 
- aquatic (water bodies), 
- clearcut and regeneration, 
- bare soil and 
- unclassified

To calculate the mean Kc values ​​per land cover class, I am using a spatial analysis technique in ArcGIS Pro (Zonal Statistics) to sample values from your fraction maps. I understand that your product offers a Kc fraction map for forest, irrigated crops and other land use type respectively. Given that my land cover classes don't exactly matches the one from your product, I was wondering what the appropriate approach would be if I wanted to make sure that I sampled the Kc value from the appropriate Kc fraction map. For example, can I simply run a zonal statistics using one Kc fraction map for forests (cropcoef_f.nc) or should change the Kc fraction map based on the LULC that I am analyzing. Here is what I had in mind:

Forest = cropcoef_f.nc
agricultural = cropcoef_i.nc
humid = cropcoef_o.nc
anthropogenic = cropcoef_o.nc,
aquatic = cropcoef_o.nc,
clearcut and regeneration = cropcoef_f.nc,
bare soil = cropcoef_o.nc
unclassified = cropcoef_o.nc

or

Forest = cropcoef_f.nc
agricultural = cropcoef_f.nc
humid = cropcoef_f.nc
anthropogenic = cropcoef_f.nc,
aquatic = cropcoef_f.nc,
clearcut and regeneration = cropcoef_f.nc,
bare soil = cropcoef_f.nc
unclassified = cropcoef_f.nc

I hope my question is clear. For context, my study area is mostly forested and remote. When I compare Kc values in one land cover type between the different fraction maps, I notice different values so I am not sure how the choice of crop coefficient map would effect my analysis. Any additional information about the difference between each fraction map would be appreciated.

Thank you very much for your help and this amazing product!

**Comment by StefaniaGrimaldi** [comment]
Dear @pierrejonathan,

Thank you for your interest in OS LISFLOOD and for your enquiry.

The crop coefficient maps are tied to the fraction maps.

This page of the user guide https://ec-jrc.github.io/lisflood-code/4_Static-Maps_land-use-depending/ explains the use of the crop coefficient maps within the hydrological model: crop coefficient maps are required to compute plant transpiration (https://ec-jrc.github.io/lisflood-model/2_07_stdLISFLOOD_plant-water-uptake/ ). We highlight that the modelling of such process also requires crop group number maps.

OS LISFLOOD is capable of modelling 6 different land use types, the modelling of plant transpiration requires crop coefficient (and crop group number) maps for  forest, irrigated, and other. 
As mentioned above, crop coefficient maps must be consistent with the fraction maps. If our understanding is correct, you generated your own land use fraction maps, therefore, it is important to ensure the consistency with the crop coefficient maps.

For this purpose, you might be interested in the detailed description provided here https://ec-jrc.github.io/lisflood-code/4_Static-Maps_land-use-depending/ :  this page explains which classes of the source datasets were selected to generate the crop coefficient map for each land use fraction. 
The comparison between the classes of your own source dataset and the classes listed in the page above should provide useful guidance to generate the three crop coefficient maps for your study. This is expected to help you refine the first solution identified in your message.

We hope that our answer helps,
on behalf of the developers team,
kind regards,
Stefania

**Comment by pierrejonathan** [comment]
> Dear @pierrejonathan,
> 
> Thank you for your interest in OS LISFLOOD and for your enquiry.
> 
> The crop coefficient maps are tied to the fraction maps.
> 
> This page of the user guide https://ec-jrc.github.io/lisflood-code/4_Static-Maps_land-use-depending/ explains the use of the crop coefficient maps within the hydrological model: crop coefficient maps are required to compute plant transpiration (https://ec-jrc.github.io/lisflood-model/2_07_stdLISFLOOD_plant-water-uptake/ ). We highlight that the modelling of such process also requires crop group number maps.
> 
> OS LISFLOOD is capable of modelling 6 different land use types, the modelling of plant transpiration requires crop coefficient (and crop group number) maps for forest, irrigated, and other. As mentioned above, crop coefficient maps must be consistent with the fraction maps. If our understanding is correct, you generated your own land use fraction maps, therefore, it is important to ensure the consistency with the crop coefficient maps.
> 
> For this purpose, you might be interested in the detailed description provided here https://ec-jrc.github.io/lisflood-code/4_Static-Maps_land-use-depending/ : this page explains which classes of the source datasets were selected to generate the crop coefficient map for each land use fraction. The comparison between the classes of your own source dataset and the classes listed in the page above should provide useful guidance to generate the three crop coefficient maps for your study. This is expected to help you refine the first solution identified in your message.
> 
> We hope that our answer helps, on behalf of the developers team, kind regards, Stefania

Thanks a lot for the quick reply, that did help me understand. After reading the detailed description, I had one follow up question. Could you describe how are aquatic land use classes considered? I'm wondering if I should set them to Null or assign a value of 0 for those.

**Comment by StefaniaGrimaldi** [comment]
Dear @pierrejonathan,

thank you for your feedback.

The land use fraction open water is specifically relevant for the computation of evaporation from open water bodies (https://github.com/ec-jrc/lisflood-code/blob/master/src/lisflood/hydrological_modules/evapowater.py). The land use fraction open water must be consistent with the map lakemask (https://ec-jrc.github.io/lisflood-code/4_Static-Maps_land-use/).

LISFLOOD can read crop coefficient (and crop group number) maps only for forest, irrigated, other. The code does not accept missing values (Null) within the computational domain. It is recommended to fill missing values (e.g. crop coefficient value for a pixel with fraction open water = 1.0) using the global mean value of the same field (note above figure 15: https://ec-jrc.github.io/lisflood-code/4_Static-Maps_land-use-depending/).

Please do not hesitate to request further clarifications, 
on behalf of the developers team, 
kind regards, Stefania

**Comment by pierrejonathan** [comment]
Thanks really appreciate your clarifications on this. For now I will mostly be needing the crop coefficient maps for my project but if I need to do further modelling I'll definitely dig deeper into OS LISFLOOD. 

Best,

Jonathan
