### ISSUE TITLE
OverflowError

### ISSUE THREAD

**Issue by EdgarEspitia** [ec-jrc/lisflood-code#166]
Dear developers of LISFLOOD,
I am running LISFLOOD for different scenarios of precipitation and temperature. But in a couple of catchments I am getting the 
errors  `OverflowError: Python int too large to convert to C long` and `OverflowError: time values outside range of 64 bit signed integers. `  Please have a look at the report file [error_lisflood.txt](https://github.com/user-attachments/files/16362866/error_lisflood.txt) . 

Any suggestion on how to fix it?

Thanks
Edgar

**Comment by doc78** [comment]
Dear Edgar
Log file indicates that there is probably an issue with meteo maps. Please check that your maps are not corrupted and the time variable is correct.
Cheers
Carlo

**Comment by EdgarEspitia** [comment]
Dear Carlo,

I managed to solve the problem by cutting the mete maps again. Occasionally (in my case, around 1-3% of the time), when I cut the maps, the output map is corrupted and lacks the variable that was supposed to be included.
Thanks
Edgar
