### ISSUE TITLE
code getting first row/column of mask is fragile 

### ISSUE THREAD

**Issue by domeniconappo** [ec-jrc/lisflood-code#18]
@emiliano-gelati 

Ciao Emiliano,
Droughts group is having troubles with lisflood, mainly because of this code:

https://github.com/ec-jrc/lisflood-code/blob/master/src/lisflood/hydrological_modules/miscInitial.py#L23-L30

Some debug output might clarify the issue:

```
> /home/development/lisflood-code/src/lisflood/hydrological_modules/miscInitial.py(27)coordinatesLand()
     26     ipdb.set_trace()
---> 27     half_cell = maskmapAttr['cell'] / 2.
     28     top_row = np.where(northings_forcing == maskmapAttr['y'] - half_cell)[0][0]

ipdb> maskmapAttr
{'y': 37.3, 'x': -25.399999999999977, 'cell': 0.1, 'col': 888, 'row': 721}
ipdb> northings_forcing
array([ 89.95,  89.85,  89.75, ..., -59.75, -59.85, -59.95])
ipdb> eastings_forcing
array([-179.95, -179.85, -179.75, ...,  179.75,  179.85,  179.95])
ipdb> n
> /home/development/lisflood-code/src/lisflood/hydrological_modules/miscInitial.py(28)coordinatesLand()
     27     half_cell = maskmapAttr['cell'] / 2.
---> 28     top_row = np.where(northings_forcing == maskmapAttr['y'] - half_cell)[0][0]
     29     left_col = np.where(eastings_forcing == maskmapAttr['x'] + half_cell)[0][0]

ipdb> maskmapAttr['y'] - half_cell
37.25
ipdb> maskmapAttr['x'] - half_cell
-25.449999999999978
```

As you see there is a problem with mask map (Africa area). This code fails to find top_row `top_row = np.where(northings_forcing == maskmapAttr['y'] - half_cell)[0][0]`

It seems too fragile to me...can it be more flexible? 
Problem at the moment is that if maskmap is not cut exactly at a certain lat/lon of a forcing, that code will never find slices of coordinates.

Can you suggest even any temporary work around?
Thank you!

**Comment by emiliano-gelati** [comment]
The problem is caused by a rounding error. To avoid these rounding errors, I have used the same approach as in
https://github.com/ec-jrc/lisflood-code/blob/master/src/lisflood/global_modules/add1.py#L122

https://github.com/ec-jrc/lisflood-code/commit/153aa794f7a2747753065b39bdf9235d1146b9c2 may solve it. Please let them try it with their setup and let me know.

**Comment by domeniconappo** [comment]
Hi @emiliano-gelati 
it worked but I had to add some other rounding.
You can check last commits and tell me if something is wrong. 

I'm going to execute tests on this branch and if they pass I will merge (unless you find something weird in latest commits).

**Comment by emiliano-gelati** [comment]
Hi @domeniconappo 
Your changes (bed85e164b2a97d75802889e06e426d9811d120d) look OK to me.
If tests are OK too, please go ahead and merge.

**Comment by domeniconappo** [comment]
Test runs fine and branch was merged into master.
