### ISSUE TITLE
‘end maps’ can't be used as initial conditions maps for another simulation 

### ISSUE THREAD

**Issue by carolinarias** [ec-jrc/lisflood-code#21]
The ‘end maps’ produced can't be used as initial conditions maps for another simulation because there are written as i.e: 
>  

> scova.end.nc

with the dot before "end".

We think the error is due to the function os.path.splitext in  add1.py", line 343, that is splitting wrongly the path due to the additional dot in the filename.  

When trying to use these files, It gives the following error:
```
Traceback (most recent call last):
  File "src/lisf1.py", line 267, in <module>
    sys.exit(main())
  File "src/lisf1.py", line 252, in main
    Lisfloodexe(settings, optionxml)
  File "src/lisf1.py", line 106, in Lisfloodexe
    Lisflood = LisfloodModel()
  File "/home/development/lisflood-code/src/lisflood/Lisflood_initial.py", line 130, in __init__
    self.snow_module.initial()
  File "/home/development/lisflood-code/src/lisflood/hydrological_modules/snow.py", line 74, in initial
    SnowCoverCInit = loadmap('SnowCoverCInitValue')
  File "/home/development/lisflood-code/src/lisflood/global_modules/add1.py", line 343, in loadmap
    cut0, cut1, cut2, cut3 = mapattrNetCDF(filename)
  File "/home/development/lisflood-code/src/lisflood/global_modules/add1.py", line 120, in mapattrNetCDF
    nf1 = iterOpenNetcdf(filename, "Checking netcdf map \n", 'r')
  File "/home/development/lisflood-code/src/lisflood/global_modules/zusatz.py", line 942, in iterOpenNetcdf
    return remoteInputAccess(access_function, file_path, error_msg)
  File "/home/development/lisflood-code/src/lisflood/global_modules/zusatz.py", line 975, in remoteInputAccess
    raise LisfloodFileError(file_path, error_msg)
lisflood.global_modules.zusatz.LisfloodFileError: 

 ======================== LISFLOOD FILE ERROR ===========================
Checking netcdf map 
path: /media/sf_vm_shared/oceania/init exists
but filename: scovc.nc does not
file name extension can be .map or .nc
```
We suggest to add a option on which the user can simply ask LISFLOOD to produce the 'end maps' or not, and an automatic way to read these without the need to change the name of the initial condition maps every time from ".end" or without. 

@valeriolorini and @domeniconappo are already aware of this issue.

**Comment by emiliano-gelati** [comment]
Hi @carolinarias, @domeniconappo, @valeriolorini,

Please double-check this.

I have run a small test with the following entry in the settings file:
`<textvar name="SnowCoverAInitValue" value="/DATA/scova.end.nc">`
The map was loaded correctly.

Also, `os.path.splitext` does the expected job:
`os.path.splitext('/data/file.end.nc')`
`('/data/file.end', '.nc')`

While running the test, I have found that some end-map entries were missing in the settings file:
"ChanQEnd", "OFDirectEnd", "OFForestEnd", "DSLRForestEnd", "OFIrrigationEnd"
Without these, the "repEndMaps" would yield exceptions.
See changes in https://github.com/ec-jrc/lisflood-code/commit/b8f4c7b3f25a0ad344c9a073e7d082521dd77a29

**Comment by carolinarias** [comment]
Dear @emiliano-gelati 

I'll try to explain myself better:

On the settings file, we have never put ``.nc`` in any of the names of the init maps. So, for example: 
``<textvar name="SnowCoverCInitValue" value="/DATA/scovc.end">``

On the settings-file documentation, is not written to do so. As a consequence, being ``value`` : ``value="/DATA/scovc.end">`` , the function os.path.splitext gives:  
``os.path.splitext("/DATA/scova.end")`` 
``('/DATA/scova', 'end')``

Then, in line 341 in add1.py:
``filename = os.path.splitext("/DATA/scovc.end")[0] + '.nc'`` 
``('/DATA/scova.nc)`` without the ".end" , as it is reported in the error.

**Comment by domeniconappo** [comment]
@emiliano-gelati 
Hi emiliano, thanks for checking this.

We used a settings file with all those end-map entries you added in https://github.com/ec-jrc/lisflood-code/commit/b8f4c7b3f25a0ad344c9a073e7d082521dd77a29 (I've added them).

Anyway, I confirm it should work with "/DATA/mapname.end.nc" (that is: including the extension) but if we use `mapname.end` as you did it here https://github.com/ec-jrc/lisflood-code/blob/master/src/settingsEUMerged.xml#L2999 (I've actually merged already (!)) it won't find the file because it just splits out the extension and add .nc (resulting in mapname.nc instead of mapname.end.nc) .

**Comment by emiliano-gelati** [comment]
@carolinarias:
The model requires the input entries pointing at end maps, which have been output by a previous model run, to end with ".end.nc" - for example:
`<textvar name="SnowCoverCInitValue" value="/DATA/scovc.end.nc">`
Please try to update your settings file accordingly.
I understand that the documentation should be updated about this. Thanks for pointing it out.

@domeniconappo:
The settings entries added in b8f4c7b provide the names of the output files where end maps are written. The ".nc" extension should not be included there, as the files could be in PCRaster format as well.

I am removing the "bug" flag and closing the issue. A documentation issue might be opened instead.

**Comment by domeniconappo** [comment]
@emiliano-gelati 
Thanks for clarifying!!

I will try to update settings file docs to better describe this process,

**Comment by carolinarias** [comment]
Thank you @emiliano-gelati  and @domeniconappo for your answers. In any case, please consider modifying the code in such a way that is not necessary to change the settings file by renaming all init map, each time a user needs to run a warm start using end maps, and then without. 

Thanks again!

**Comment by nikhilteja91** [comment]
@carolinarias @emiliano-gelati @domeniconappo could you please help me in installing and running LISFLOOD?  I tried many ways installing it, but I failed. Everytime it keeps giving me errors. I will be forever grateful to you if you help me.
