### ISSUE TITLE
Wrong link

### ISSUE THREAD

**Issue by carolinarias** [ec-jrc/lisflood-code#33]
On https://pypi.org/project/lisflood-model/, The "Homepage" link is [https://github.com/ec-jrc/lisflood-model](https://github.com/ec-jrc/lisflood-model), when it should be [https://github.com/ec-jrc/lisflood-code](https://github.com/ec-jrc/lisflood-code)?

See also see https://github.com/ec-jrc/lisflood-code/blob/ab02797d70735e9d0cdbee5bd86d549b200dc316/setup.py#L135

**Comment by domeniconappo** [comment]
@carolinarias good catch! thank you
