### ISSUE TITLE
optimizations - round 1

### ISSUE THREAD

**Issue by domeniconappo** [ec-jrc/lisflood-code#44]
There is some code in lisflood where is possible to apply some (micro) optimizations. 
I estimate to save 4/5% of time.

e.g. Avoid using numpy.copy for zero arrays that are used in np.where() operations.

This is a clean-up for next optimizations tasks: i.e. I/O optimizations + parallel computations.

Notes:
Using cprofile, pytest-profiling, pyprof2calltree, KCacheGrind for performances analysis.

**Comment by salampe** [comment]
@domeniconappo Thanks! Sounds good but lets first see how and when to introduce these optimizations in our overall OS LISFLOOD development plan (@valeriolorini )

**Comment by domeniconappo** [comment]
ECMWF is investigating on I/O optimizations
