### ISSUE TITLE
Number/Description soil layers

### ISSUE THREAD

**Issue by TM-GIT-HUB** [ec-jrc/lisflood-code#47]
THANKS FOR THE GREAT WORK YOU ARE DOING!!!

My issue is as follows:
It is not quite clear if LISFLOOD uses 2 or 3 layers for soil water storage/flux calculations and what these layers represent. This should be clarified, if possible in the code, the documentation and the settings file:
- The documentation (https://ec-jrc.github.io/lisflood-code/4_annex_input-files/) says 2 layers, with the first layer provided separately for "forest" and "other"
  (e.g., ThetaSat1 for forest, 	ThetaSat1 for other, ThetaSat2 for forest and other)
- The source code uses 3 layers (soil.py)
  # Soil moisture content at saturation [V/V]
  ThetaRes1a = defsoil('MapThetaRes1', 'MapThetaRes1Forest')
  ThetaRes1b = defsoil('MapThetaRes2', 'MapThetaRes2Forest')
  ThetaRes2 = defsoil('MapThetaRes3')
- The settings file (settings_tpl.xml) uses 3 layers, although the 2nd and 3rd share the same description:
  <textvar name="ThetaForestInit1Value" value="-9999">
      <comment>
          initial soil moisture content layer 1
          -9999: use field capacity values
      </comment>
  </textvar>

  <textvar name="ThetaForestInit2Value" value="-9999">
      <comment>
          initial soil moisture content layer 2
          -9999: use field capacity values
      </comment>
  </textvar>

  <textvar name="ThetaForestInit3Value" value="-9999">
      <comment>
          initial soil moisture content layer 2
          -9999: use field capacity values
      </comment>
  </textvar>

**Comment by salampe** [comment]
Thanks for this comment. Indeed, we are aware that there are inconsistencies in the model documentation and the latest model version regarding soil moisture. We have started updating the model documentation (for example see here where it already refers to three soil layers: https://ec-jrc.github.io/lisflood-model/2_stdLISFLOOD_soilmoisture-redistribution/ ) It might be, however, that some parts of the documentation still refer to two soil layers. We will keep on updating the model doc.

**Comment by TM-GIT-HUB** [comment]
Thanks for the fast response!!! So am I understanding things right saying it is 3 soil layers and 1a,1b,2 in the code refer to a topsoil and two subsoil layers? Thank you very much for your support!

**Comment by salampe** [comment]
Yes, correct! It is a superficial soil layer, upper soil layer and lower soil layer.

**Comment by salampe** [comment]
Update of model documentation is continuously and ongoing
