### ISSUE TITLE
Input data methodology

### ISSUE THREAD

**Issue by simonmoulds** [ec-jrc/lisflood-code#51]
A student of mine at Imperial College is developing an application of Lisflood for Africa. Many of the required inputs are self-explanatory or have been documented previously (e.g. https://publications.jrc.ec.europa.eu/repository/bitstream/JRC78917/lisflood_2013_online.pdf). But, it seems that Lisflood now requires the depth of three soil layers.

Please could you tell me the best way to estimate soil depth for Lisflood?

A more general point is the need to update the documentation to suggest the available input data and methods for computing the various input requirements. I can help with this, as I've written scripts to prepare almost all the required maps (not water use).

**Comment by simonmoulds** [comment]
Just read #47 about soil layers, but the second point still stands - if I can be of any help then let me know.

**Comment by salampe** [comment]
Dear @simonmoulds ,

Please have a look also at the document here: https://ec-jrc.github.io/lisflood/pdfs/Dataset_hydro.pdf  This document is also bit outdated but explains how some of the soil maps for Europe have been generated. For soil data for Africa I would recommend to use https://www.isric.org/ 

We have also recently updated the LISFLOOD model documentation so that it correctly refers to the three required soil layers.

Your help to update the documentation on creating the available input data is highly appreciated. @domeniconappo I just realized that the model documentation is on a private repo. Can you make it public? Then @simonmoulds can simply create a pull request and we will review and then, if approved, merge into the main branch.

**Comment by emiliano-gelati** [comment]
Hi @simonmoulds ,

To estimate soil layer thicknesses, you may want to consider the following model assumptions:
- The 1st (top) and 2nd (middle) layers constitute the root zone. Some processes, such as macro-pore flow and evapotranspiration, are simulated based on total root zone soil moisture, i.e. the sum of soil water contents of layers 1 and 2.
- In several applications, we assume the 1st soil layer depth to be comparable with the penetration depth of remote sensing soil moisture sensors, usually of the order of 10<sup>0</sup>--10<sup>1</sup> cm.
- The 3rd (bottom) layer represents the deep soil (normally unsaturated) not spanned by roots.

Soil layer thicknesses have to be provided for two land cover classes: "forest" for tall natural vegetation; and "other" for short natural vegetation, crops and bare soil. The [relevant settings entries](https://github.com/ec-jrc/lisflood-code/blob/master/src/settings_tpl.xml#L3991-L4035) are: SoilDepth1Forest, SoilDepth2Forest, SoilDepth3Forest ("forest"); and SoilDepth1, SoilDepth2, SoilDepth3 ("other")

**Comment by simonmoulds** [comment]
@salempe - thanks a lot for pointing me to that document - I'll compare my approaches with the ones it describes. And if you open up the repo then I'll be happy to add whatever I have in due course. I'll also put the various scripts (GRASS GIS + Python) I used on my own Github.

@emiliano-gelati - thanks for this. Considering the document that @salampe highlighted, an approach would therefore be to compute the root depth for forest/other, set SoilDepth1 to somewhere between 100-10mm and subtract this from root depth to get SoilDepth2. Then for SoilDepth3, I can take the depth to bedrock from this dataset - https://daac.ornl.gov/SOILS/guides/Global_Soil_Regolith_Sediment.html - and subtract the root depth. Does that sound sensible?

Thanks both for your help - I really appreciate it.

**Comment by domeniconappo** [comment]
@simonmoulds

https://github.com/ec-jrc/lisflood-model is public now.
Feel free to contact me directly if you need any info on how to integrate your changes.

Thanks a lot for your interest!

**Comment by behailuhussen** [comment]
How can i get the LISFLOOD model freely

**Comment by valeriolorini** [comment]
@behailuhussen, this is (almost) the right place, the main page for installing the model is at https://github.com/ec-jrc/lisflood-code, if you scroll down the page you'll see a readme section and a quick installation guide. For a wider set of information about the model you can go to https://ec-jrc.github.io/lisflood/.
