### ISSUE TITLE
Fixes for warm start

### ISSUE THREAD

**Issue by ecCinziaMazzetti** [ec-jrc/lisflood-code#55]
Bug-fix for warm start:

1. All netCDF files saved as double precision
2. Change data_format in writenet to double
3. Add state maps for LakePrevOutflow and LakePrevOutflow
4. Bug-fix routing for negative v and Q at the end of computation step

5. Fix initialization of DSLR for warm start
6. Update state variable Theta1a[2] after changes to variable W1a[2] due to water abstraction for irrigation
7. Add output for chanq time series

8. Update settings.xml

**Comment by cinziamazzetti** [comment]
9. Changes to routing for Copernicus branch

**Comment by cinziamazzetti** [comment]
9. Changes to routing for Copernicus branch

**Comment by cinziamazzetti** [comment]
9. Changes to routing for Copernicus branch

**Comment by cinziamazzetti** [comment]
9. Changes to routing for Copernicus branch

All fixes implemented and tested.

**Comment by cinziamazzetti** [comment]
9. Changes to routing for Copernicus branch

All fixes implemented and tested.
