### ISSUE TITLE
Add unit/e2e tests

### ISSUE THREAD

**Issue by domeniconappo** [ec-jrc/lisflood-code#61]
To add to the suite:

1. warm start test
run a continuously for at least 6 month
run on the same period but restarting LISFLOOD at every step (start and stop)
Compare ALL state maps at the end of the run and one day for each month. They must be identical.
Test must be performed with daily steps and with 6-hourly steps.
Test must be repeated using steps instead of dates.

2. Sub-catchment
Run entire domain, then run one subcatchment for the same period of time. Compare ALL state maps. Results must be identical. 

Important note: The test should fail when wateruse=1.

This test demonstrates that wateruse module introduces incongruities between running the model on subcatchments and on the entire domain (GloFAS)

3. Initrun
Run LISFLOOD initrun over a period of at least 2 years and compare avgdis and lzavin files with bechmark run. Results must be identical.

**Comment by StefaniaGrimaldi** [comment]
WARM START on Jan 01 1996

**************************************************************
FILE PATHS
**************************************************************
</comment>

<textvar name="PathOut" value="outputs/1996-2000/">
<comment>
Output path (org=$(PathRoot)/out)
</comment>
</textvar>

**<textvar name="PathInit" value="outputs/1990-1995/">**
<comment>
Path of the initial value maps e.g. lzavin.map (org=$(PathRoot)/outPo)
</comment>
</textvar>
