### ISSUE TITLE
SystemError: gdal-config not found.GDAL seems not installed. Please, install GDAL binaries and libraries for your system and then install the relative pip package.

### ISSUE THREAD

**Issue by nikhilteja91** [ec-jrc/lisflood-code#68]
I have tried many ways for installing LISFLOOD, but i failed. Everytime "gdal-config" error is the problem i am facing. Could you please instruct me on how to install LISFLOOD from scratch?

I am doing this in Windows10 and Anaconda distribution and python 3.7 environment. I have even installed GDAL from https://sandbox.idre.ucla.edu/sandbox/tutorials/installing-gdal-for-windows.

![gdal error](https://user-images.githubusercontent.com/70052517/105537903-a5f7a280-5d18-11eb-86e2-bc88e7c640db.jpg)

**Comment by valeriolorini** [comment]
Dear nikhilteja91 , as far as I understand you are trying to run lisflood on a windows 10 machine. Libraries used in some part of Lisflood code are 'challenging' to install on windows, as you can read in the issue https://github.com/ec-jrc/lisflood-code/issues/17#issue-452987442 . I'd suggest to install the ''linux-box'' on your windows 10 machine (https://docs.microsoft.com/en-us/windows/wsl/about) and install lisflood there, if it's feasible for you.

**Comment by nikhilteja91** [comment]
> Dear nikhilteja91 , as far as I understand you are trying to run lisflood on a windows 10 machine. Libraries used in some part of Lisflood code are 'challenging' to install on windows, as you can read in the issue [#17 (comment)](https://github.com/ec-jrc/lisflood-code/issues/17#issue-452987442) . I'd suggest to install the ''linux-box'' on your windows 10 machine (https://docs.microsoft.com/en-us/windows/wsl/about) and install lisflood there, if it's feasible for you.

I have installed GDAL from here
https://sandbox.idre.ucla.edu/sandbox/tutorials/installing-gdal-for-windows

Even then, I am getting errors when "compile_kinematic_wave_parallel_tools.py" is run. I am also getting errors with the CALENDARS when settings (XML) file is run. There are a lots of issues installing LISFLOOD. Looks like some classes in the modules have become obsolete. I am unable to install it using pip. So, downloaded the source code and saved in "site-packages" folder.

Now this is where I am. Fighting to solve the erros.
![calendar error](https://user-images.githubusercontent.com/70052517/105611690-af4a4300-5ddc-11eb-87d8-789c10c27cf8.jpg)

**Comment by domeniconappo** [comment]
Hi, unfortunately we don't support Windows actively because of issues with conda + gdal.

Anyway, this new error seems to be related to cftime version different from requirements.

Can you just execute the following command (ensure you activated  the conda env/virtualenv you created for lisflood):

pip install cftime==1.0.4.2

And then try again?
Thank you.

**Comment by nikhilteja91** [comment]
It worked!!! Thank you. I am able to run LISFLOOD in windows right now. If I get any issues, I will get back to you.

**Comment by nikhilteja91** [comment]
Now i have a

**Comment by Sailor596** [comment]
> I have tried many ways for installing LISFLOOD, but i failed. Everytime "gdal-config" error is the problem i am facing. Could you please instruct me on how to install LISFLOOD from scratch?
> 
> I am doing this in Windows10 and Anaconda distribution and python 3.7 environment. I have even installed GDAL from https://sandbox.idre.ucla.edu/sandbox/tutorials/installing-gdal-for-windows.
> 
> ![gdal error](https://user-images.githubusercontent.com/70052517/105537903-a5f7a280-5d18-11eb-86e2-bc88e7c640db.jpg)

Dear nikhilteja91, I am getting the same error. Can you help me? I couldn't solve the GDAL problem.

**Comment by Sailor596** [comment]
> I have tried many ways for installing LISFLOOD, but i failed. Everytime "gdal-config" error is the problem i am facing. Could you please instruct me on how to install LISFLOOD from scratch?
> 
> I am doing this in Windows10 and Anaconda distribution and python 3.7 environment. I have even installed GDAL from https://sandbox.idre.ucla.edu/sandbox/tutorials/installing-gdal-for-windows.
> 

![Error](https://user-images.githubusercontent.com/111195948/184545124-c23ac68e-941a-4426-948b-d7261a301d71.jpg)


I downloaded the files from this page (https://sandbox.idre.ucla.edu/sandbox/tutorials/installing-gdal-for-windows.) but I keep getting the error in the picture. How did you set it up?
