### ISSUE TITLE
settings_tpl.xml

### ISSUE THREAD

**Issue by corentincarton** [ec-jrc/lisflood-code#75]
Hi,

I realised I couldn't install the latest version. It requires in setup.py the "src/settings_tpl.xml" file, which I couldn't find. It seems it was renamed to lisfloodSettings_reference.xml but I'm not 100% sure... If that's the case, it should be simply changed in setup.py.

Cheers,
Corentin

**Comment by domeniconappo** [comment]
Hi Corentin, 
thanks for reporting!

**Comment by domeniconappo** [comment]
Published a 3.0.1.post1 version on pypi.
To install:

`pip install -U lisflood-model`
