### ISSUE TITLE
Dependencies cleanup and drop python2 support

### ISSUE THREAD

**Issue by corentincarton** [ec-jrc/lisflood-code#78]
Hi,

As discussed, I believe these three points should be addressed in the near future to make the code more readable, and allow easier development and deployment of LISFLOOD-OS:
1. Drop the Python2 support and cleanup the code by removing the Python dependencies lines/functions (based on nine, etc.)
2. Revise the list of package requirements and remove the non-essential ones
3. Change strong package dependencies in the requirements (package == vX.X.X) to allow more flexibility (use >= and <= instead)

These three points could be addressed in the same branch/release and I would recommend to do the same for the lisflood-utilities and lisflood-calibration repositories.

Cheers,
Corentin

**Comment by doc78** [comment]
Quick update about the requirements.txt list of packages: all of them have now the ">=" instead the "==" to enable package flexibility.

The only package limited is importlib-metadata<5.0.0, needed to avoid the issue of the list_engine() function in xarray package while opening the netCFD4 files.
