### ISSUE TITLE
cannot stat /tests/data/TestCatchment

### ISSUE THREAD

**Issue by vigouredelaruse** [ec-jrc/lisflood-code#88]
hi there
following the docker installation instructions here https://ec-jrc.github.io/lisflood-code/3_step2_installation/ fails for me, possibly due to not having read the relevant code

docker run -v /src/lisflood-fp:/usecases efas/lisflood:latest usecases 
cp: cannot stat '/tests/data/TestCatchment': No such file or directory

specifying the volume another way
PS C:\src\lisflood-fp> docker volume create usecases
usecases
PS C:\src\lisflood-fp> docker run -v usecases:/usecases efas/lisflood:latest usecases
Copying test catchments to /usecases/...
cp: cannot stat '/tests/data/TestCatchment': No such file or directory

note the following refers to a dead link 
![image](https://user-images.githubusercontent.com/31052867/142564030-368bd9a9-034c-4581-a0c5-e396244e2a36.png)

please advise

**Comment by StefaniaGrimaldi** [comment]
Hi @vigouredelaruse,

thanks for your interest in using LISFLOOD-OS.

We are aware of an issue when trying to use the Docker with LISFLOOD-OS v3.1. We will solve the problem as soon as possible. 

In the meantime, we would like to invite you to follow either option B (pypi package) or option C (source code): https://ec-jrc.github.io/lisflood-code/3_step2_installation/

Regarding the second point of your message, you can find all the files to run a test here :
https://github.com/ec-jrc/lisflood-code/tree/master/tests/data/LF_ETRS89_UseCase
https://github.com/ec-jrc/lisflood-code/tree/master/tests/data/LF_lat_lon_UseCase
The first one is the Po basin in Italy, the second one is the Fraser catchment in Canada (https://github.com/ec-jrc/lisflood-usecases/)

"TestCatchment" generally refers to the folder name of the test data. We will clarify this in the instructions, thank you for pointing it out.

We will be pleased to do our best to answer your questions and make sure that you can run LISFLOOD-OS on your pc.

Kind regards,
Stefania
(Stefania.GRIMALDI@ec.europa.eu)

**Comment by vigouredelaruse** [comment]
nice to see that not only is the shingle out but the dr is in! thanks for getting back to me so quickly. i'm no ..er whatever specialty it is that uses Lisflood-FP but i want to democratize the process with a simple google maps style flood prediction site incorporating SAR and DEM to predict flooding in arbitrary regions - would you mind telling me if 'arbitrary regions' is a suitable fit for LISFLOOD-FP?

**Comment by StefaniaGrimaldi** [comment]
Dear @vigouredelaruse,
we cannot answer your question as this is the repository of the **LISFLOOD-OS hydrological rainfall-runoff model**.
Your message refers to a different model: the 2-dimensional hydrodynamic model LISFLOOD-FP.
Stefania
